language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - "node"
git:
  depth: 5
before_install:
  - npm i -g npm@latest
  - npm i -g yarn
install:
  - yarn
script:
  - yarn run test
# after_success: yarn run coveralls
